name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v6
     

        - name: List and Readfiles
          run: |
               echo "My First GH Action Job"
               ls -ltra
               cat README.md

  #      - name: List Files
  #        run: ls

  #      - name: Read File
  #        run: cat README.md


           